export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_FAILURE = 'FETCH_PLANETS_FAILURE';
export const SORT_PLANET_LIST = 'SORT_PLANET_LIST';
export const FILTER_PLANET_LIST_BY_NAME = 'FILTER_PLANET_LIST_BY_NAME';
export const REMOVE_SINGLE_COMPARISON_CRITERIA =
  'REMOVE_SINGLE_COMPARISON_CRITERIA';
export const CLEAR_COMPARISON_CRITERIA = 'CLEAR_COMPARISON_CRITERIA';
export const FILTER_PLANET_LIST_BY_COMPARISON =
  'FILTER_PLANET_LIST_BY_COMPARISON';
